### ISSUE TITLE
Can't build the Debian .deb package

### ISSUE THREAD

**Issue by TechyEd** [KostyaEsmukov/afancontrol#12] opened 2023-12-07 17:32 UTC
Hi!
Before anything, thank you for your time and effort to create this project.
Well, I'm hitting an error trying to build the afancontrol .deb package.

I'm using a clean Debian 12 install, but getting the following error:

`https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz.asc failed: 404 NOT FOUND`

Here's the whole output:

```
ed@debian:~/afancontrol$ sudo make deb-from-pypi
find . -name "*.pyc" -print0 | xargs -0 rm -f
rm -Rf dist
rm -Rf *.egg-info
docker build -t afancontrol-debuild -f ./Dockerfile.debian .
[+] Building 1.9s (13/13) FINISHED                                                                                  docker:default
 => [internal] load build definition from Dockerfile.debian                                                                   0.1s
 => => transferring dockerfile: 840B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                             0.0s
 => => transferring context: 45B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/debian:unstable                                                            1.2s
 => [1/8] FROM docker.io/library/debian:unstable@sha256:8a91c489073e6a253fa744ae3eaa280978eb6276635e184937550c0488bdbbae      0.0s
 => [internal] load build context                                                                                             0.1s
 => => transferring context: 520B                                                                                             0.0s
 => CACHED [2/8] RUN apt-get update     && apt-get install -y         build-essential         debhelper         devscripts    0.0s
 => CACHED [3/8] RUN mkdir ~/.gnupg && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf                                           0.0s
 => CACHED [4/8] RUN gpg --recv-keys "AA7B5406547AF062"                                                                       0.0s
 => CACHED [5/8] COPY debian /build/afancontrol/debian                                                                        0.0s
 => CACHED [6/8] WORKDIR /build/afancontrol/                                                                                  0.0s
 => CACHED [7/8] RUN mkdir -p debian/upstream     && gpg --export --export-options export-minimal --armor         'A18FE9F6F  0.0s
 => CACHED [8/8] RUN apt-get -y build-dep .                                                                                   0.0s
 => exporting to image                                                                                                        0.0s
 => => exporting layers                                                                                                       0.0s
 => => writing image sha256:5176257b209f6662e6d613d0cdd08e4af1fc034c444969929c7d2d40db5e304b                                  0.0s
 => => naming to docker.io/library/afancontrol-debuild                                                                        0.0s
docker run -it --rm \
        -v `pwd`/dist:/afancontrol/dist \
        afancontrol-debuild sh -ex -c '\
                uscan --download --overwrite-download --verbose; \
                tar xaf ../afancontrol_*.orig.tar.gz --strip 1; \
                debuild -us -uc; \
                cd ../; \
                ls -alh; \
                mkdir /afancontrol/dist/debian; \
                cp afancontrol?* /afancontrol/dist/debian/; \
'
+ uscan --download --overwrite-download --verbose
uscan info: uscan (version 2.23.6) See uscan(1) for help
uscan info: Scan watch files in .
uscan info: Check debian/watch and debian/changelog in .
uscan info: package="afancontrol" version="3.1.0-1" (as seen in debian/changelog)
uscan info: package="afancontrol" version="3.1.0" (no epoch/revision)
uscan info: ./debian/changelog sets package="afancontrol" version="3.1.0"
uscan info: Found upstream signing keyring: debian/upstream/signing-key.asc
uscan info: Process watch file at: debian/watch
    package = afancontrol
    version = 3.1.0
    pkg_dir = .
uscan info: opts: uversionmangle=s/(rc|a|b|c)/~$1/,pgpsigurlmangle=s/$/.asc/
uscan info: line: https://pypi.debian.net/afancontrol/afancontrol-(.+)\.(?:zip|tgz|tbz|txz|(?:tar\.(?:gz|bz2|xz)))
uscan info: Parsing uversionmangle=s/(rc|a|b|c)/~$1/
uscan info: Parsing pgpsigurlmangle=s/$/.asc/
uscan info: line: https://pypi.debian.net/afancontrol/afancontrol-(.+)\.(?:zip|tgz|tbz|txz|(?:tar\.(?:gz|bz2|xz)))
uscan info: Last orig.tar.* tarball version (from debian/changelog): 3.1.0
uscan info: Last orig.tar.* tarball version (dversionmangled): 3.1.0
uscan info: Requesting URL:
   https://pypi.debian.net/afancontrol/
uscan info: Matching pattern:
   (?:(?:https://pypi.debian.net)?\/afancontrol\/)?afancontrol-(.+)\.(?:zip|tgz|tbz|txz|(?:tar\.(?:gz|bz2|xz)))
uscan info: Found the following matching hrefs on the web page (newest first):
   https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz (3.1.0) index=3.1.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz (3.1.0) index=3.1.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-3.0.0.tar.gz (3.0.0) index=3.0.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-3.0.0.tar.gz (3.0.0) index=3.0.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.2.1.tar.gz (2.2.1) index=2.2.1-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.2.1.tar.gz (2.2.1) index=2.2.1-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.2.0.tar.gz (2.2.0) index=2.2.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.2.0.tar.gz (2.2.0) index=2.2.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.1.0.tar.gz (2.1.0) index=2.1.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.1.0.tar.gz (2.1.0) index=2.1.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0.tar.gz (2.0.0) index=2.0.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0.tar.gz (2.0.0) index=2.0.0-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b5.tar.gz (2.0.0~b5) index=2.0.0~b5-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b5.tar.gz (2.0.0~b5) index=2.0.0~b5-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b4.tar.gz (2.0.0~b4) index=2.0.0~b4-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b4.tar.gz (2.0.0~b4) index=2.0.0~b4-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b3.tar.gz (2.0.0~b3) index=2.0.0~b3-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b3.tar.gz (2.0.0~b3) index=2.0.0~b3-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b2.tar.gz (2.0.0~b2) index=2.0.0~b2-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b2.tar.gz (2.0.0~b2) index=2.0.0~b2-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b1.tar.gz (2.0.0~b1) index=2.0.0~b1-1 
   https://pypi.debian.net/afancontrol/afancontrol-2.0.0b1.tar.gz (2.0.0~b1) index=2.0.0~b1-1 
uscan info: Looking at $base = https://pypi.debian.net/afancontrol/ with
    $filepattern = afancontrol-(.+)\.(?:zip|tgz|tbz|txz|(?:tar\.(?:gz|bz2|xz))) found
    $newfile     = https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz
    $newversion  = 3.1.0
    $lastversion = 3.1.0
uscan info: Matching target for downloadurlmangle: https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz
uscan info: Upstream URL(+tag) to download is identified as    https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz
uscan info: Filename (filenamemangled) for downloaded file: afancontrol-3.1.0.tar.gz
uscan info: Newest version of afancontrol on remote site is 3.1.0, local version is 3.1.0
uscan info:  => Package is up to date from:
             => https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz
uscan info:  => Forcing download as requested
uscan info: Downloading upstream package: afancontrol-3.1.0.tar.gz
uscan info: Requesting URL:
   https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz
uscan info: Successfully downloaded upstream package: afancontrol-3.1.0.tar.gz
uscan info: Downloading OpenPGP signature from:
   https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz.asc (pgpsigurlmangled)
   as afancontrol-3.1.0.tar.gz.asc
uscan info: Requesting URL:
   https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz.asc
uscan warn: In directory ., downloading
  https://pypi.debian.net/afancontrol/afancontrol-3.1.0.tar.gz.asc failed: 404 NOT FOUND
uscan die: FAIL Checking OpenPGP signature (no signature file downloaded).
make: *** [Makefile:67: deb-from-pypi] Erro 255
``` 
I don't know if you are still providing support for this project, but if you could give some guidance on fixing this issue I would be very grateful.

Thank you!

**Comment by limetto** [comment] 2024-01-04 22:45
I have the same issue and I have no clue how to fix this, but building the target deb-local with 'make deb-local' works for me on debian 12.

**Comment by KostyaEsmukov** [comment] 2024-01-06 12:36
Hi, thank you for letting me know about this!

This is caused by PyPI abandoning support for PGP signatures, as announced here: https://blog.pypi.org/posts/2023-05-23-removing-pgp/. Furthermore, they have taken a step further by removing even the previously uploaded signatures.

I've just pushed a fix for that, switching the `make deb-from-pypi` command to download release + the signature from GitHub releases instead of PyPI, so that should resolve the issue.

**Closed by KostyaEsmukov** 2024-01-06 12:36 UTC
